version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn eva.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - /var/www/evaproject.online/static:/home/app/web/staticfiles
      - /var/www/evaproject.online/media:/home/app/web/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - asr
      - ts
      - db

  asr:
    build: ./service_asr
    ports:
      - "5005:5005"
  ts:
    build: ./service_text_similarity
    ports:
      - "5000:5000"
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

  celery:
    build: ./app
    command: celery -A eva worker --loglevel=info
    volumes:
      - ./app:/usr/src/app
      - /var/www/evaproject.online/media:/usr/src/app/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis

  redis:
    image: redis:5-alpine

volumes:
  postgres_data:
