version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - asr
      - ts

  asr:
    build: ./service_asr
    ports:
      - "5005:5005"
  ts:
    build: ./service_text_similarity
    ports:
      - "5000:5000"
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=eva_django
      - POSTGRES_PASSWORD=eva_django
      - POSTGRES_DB=eva_django_dev

#volumes:
#  postgres_data: