version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - asr
      - ts
      - db

  asr:
    build: ./service_asr
    ports:
      - "5005:5005"
  ts:
    build: ./service_text_similarity
    ports:
      - "5000:5000"
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=eva_django
      - POSTGRES_PASSWORD=eva_django
      - POSTGRES_DB=eva_django_dev

  celery:
    build: ./app
    command: celery -A eva worker --loglevel=info
    volumes:
      - ./app:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7-alpine

  dashboard:
    build: ./app
    command: celery --app=eva flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - 5555:5555
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
      - celery

volumes:
  postgres_dev:
