version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - /var/www/eva.mldl.ru/static/:/usr/src/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - asr
      - ts
      - db
      - redis

  asr:
    build: ./service_asr
    ports:
      - "5005:5005"

  ts:
    build: ./service_text_similarity
    ports:
      - "5000:5000"

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=eva_django
      - POSTGRES_PASSWORD=eva_django
      - POSTGRES_DB=eva_django_dev

  celery:
    build: ./app
    command: celery --app=eva worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis

  redis:
    image: redis:7-alpine

  dashboard:
    build: ./app
    command: celery --app=eva flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - 5555:5555
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
      - celery

volumes:
  postgres_dev:
